CREATE TABLE tx_ieb_domain_model_statictrainer (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	verwendung_babi smallint(1) unsigned NOT NULL DEFAULT '0',
	verwendung_psa smallint(1) unsigned NOT NULL DEFAULT '0',
	lebenslauf text,
	qualifikation_babi text NOT NULL DEFAULT '',
	lehr_befugnis text NOT NULL DEFAULT '',
	qualifikation_psa1 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa2 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa3 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa4 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa5 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa6 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa7 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa8 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa text NOT NULL DEFAULT '',
	qualifikation_psa_kommentar text NOT NULL DEFAULT '',
	anerkennung_pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_comment_internal text NOT NULL DEFAULT '',
	review_comment_tr text NOT NULL DEFAULT '',
	review_status int(11) DEFAULT '0' NOT NULL,
	review_frist date DEFAULT NULL,
	lebenslauf_datei int(11) unsigned NOT NULL DEFAULT '0',
	qualifikation_babi_datei int(11) unsigned NOT NULL DEFAULT '0',
	lehr_befugnis_datei varchar(255) NOT NULL DEFAULT '',
	qualifikation_psa_datei int(11) unsigned NOT NULL DEFAULT '0',
	based_on int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_staticberater (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	lebenslauf int(11) unsigned NOT NULL DEFAULT '0',
	qualifikationsnachweise int(11) unsigned NOT NULL DEFAULT '0',
	review_comment_internal text NOT NULL DEFAULT '',
	review_comment_tr text NOT NULL DEFAULT '',
	review_status int(11) DEFAULT '0' NOT NULL,
	review_frist date DEFAULT NULL,
	standorte int(11) unsigned NOT NULL DEFAULT '0',
	based_on int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_staticstandort (
	name varchar(255) NOT NULL DEFAULT '',
	adresse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	pruef_bescheid smallint(1) unsigned NOT NULL DEFAULT '0',
	koop_schule text NOT NULL DEFAULT '',
	koop_schule_datei int(11) unsigned NOT NULL DEFAULT '0',
	review_comment_internal text NOT NULL DEFAULT '',
	review_comment_tr text NOT NULL DEFAULT '',
	review_comment_status int(11) DEFAULT '0' NOT NULL,
	review_frist date DEFAULT NULL,
	based_on int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_staticstammdaten (
	name varchar(255) NOT NULL DEFAULT '',
	nachweis int(11) unsigned NOT NULL DEFAULT '0',
	rechtsform int(11) DEFAULT '0' NOT NULL,
	strasse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	seit int(11) NOT NULL DEFAULT '0',
	website varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	telefon varchar(255) NOT NULL DEFAULT '',
	leitbild text,
	leitbild_datei int(11) unsigned NOT NULL DEFAULT '0',
	qms_zertifikat_datei int(11) unsigned NOT NULL DEFAULT '0',
	qms_zertifikat text NOT NULL DEFAULT '',
	qms_typ int(11) DEFAULT '0' NOT NULL,
	zertifikat_bis int(11) NOT NULL DEFAULT '0',
	qualitaet_sicherung text,
	qualitaet_sicherung_datei int(11) unsigned NOT NULL DEFAULT '0',
	qualitaet_personal text,
	qualitaet_personal_datei int(11) unsigned NOT NULL DEFAULT '0',
	tr_pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	pruefbescheid text,
	pruefbescheid_datei int(11) unsigned NOT NULL DEFAULT '0',
	pruefbescheid_bis int(11) NOT NULL DEFAULT '0',
	review_comment_internal text NOT NULL DEFAULT '',
	review_comment_tr text NOT NULL DEFAULT '',
	review_status int(11) DEFAULT '0' NOT NULL,
	review_frist date DEFAULT NULL,
	standorte int(11) unsigned NOT NULL DEFAULT '0',
	based_on int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_ansuchen (
	name varchar(255) NOT NULL DEFAULT '',
	version int(11) NOT NULL DEFAULT '0',
	version_based_on int(11) NOT NULL DEFAULT '0',
	version_active smallint(1) unsigned NOT NULL DEFAULT '0',
	nummer varchar(255) NOT NULL DEFAULT '',
	akkreditierung_datum datetime DEFAULT NULL,
	einreich_datum datetime DEFAULT NULL,
	zuteilung_datum varchar(255) NOT NULL DEFAULT '',
	akkreditierung_entscheidung_datum datetime DEFAULT NULL,
	typ int(11) DEFAULT '0' NOT NULL,
	bundesland int(11) DEFAULT '0' NOT NULL,
	kompetenzbereiche int(11) NOT NULL DEFAULT '0',
	kompetenzbereiche_text text NOT NULL DEFAULT '',
	uebersicht_text text NOT NULL DEFAULT '',
	uebersicht_datei int(11) unsigned NOT NULL DEFAULT '0',
	zielgruppen_ansprache text NOT NULL DEFAULT '',
	zielgruppen_ansprache_datei int(11) unsigned NOT NULL DEFAULT '0',
	fernlehre smallint(1) unsigned NOT NULL DEFAULT '0',
	kinderbetreuung smallint(1) unsigned NOT NULL DEFAULT '0',
	lernziele int(11) unsigned NOT NULL DEFAULT '0',
	lernstandserhebung int(11) unsigned NOT NULL DEFAULT '0',
	diversity int(11) unsigned NOT NULL DEFAULT '0',
	didaktik_kommentar text,
	beratung_text text,
	beratung_datei int(11) unsigned NOT NULL DEFAULT '0',
	review_b1_comment_internal text NOT NULL DEFAULT '',
	review_b1_commen_tr text NOT NULL DEFAULT '',
	review_b1_status int(11) DEFAULT '0' NOT NULL,
	review_b2_comment_internal text NOT NULL DEFAULT '',
	review_b2_comment_tr text NOT NULL DEFAULT '',
	review_b2_status int(11) DEFAULT '0' NOT NULL,
	review_c1_comment_internal text NOT NULL DEFAULT '',
	review_c1_comment_tr text NOT NULL DEFAULT '',
	review_c1_status int(11) DEFAULT '0' NOT NULL,
	review_c2_comment_internal text NOT NULL DEFAULT '',
	review_c2_comment_tr text NOT NULL DEFAULT '',
	review_c2_status int(11) DEFAULT '0' NOT NULL,
	review_c3_comment_internal text NOT NULL DEFAULT '',
	review_c3_comment_tr text NOT NULL DEFAULT '',
	review_c3_status int(11) DEFAULT '0' NOT NULL,
	review_total_comment_internal text NOT NULL DEFAULT '',
	review_total_comment_tr text NOT NULL DEFAULT '',
	review_total_status int(11) DEFAULT '0' NOT NULL,
	review_total_frist date DEFAULT NULL,
	stammdaten int(11) unsigned DEFAULT '0',
	standorte int(11) unsigned NOT NULL DEFAULT '0',
	verantwortliche int(11) unsigned NOT NULL DEFAULT '0',
	trainer int(11) unsigned NOT NULL DEFAULT '0',
	berater int(11) unsigned NOT NULL DEFAULT '0',
	kopie_von int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_standort (
	name varchar(255) NOT NULL DEFAULT '',
	adresse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	pruef_bescheid smallint(1) unsigned NOT NULL DEFAULT '0',
	koop_schule text NOT NULL DEFAULT '',
	koop_schule_datei int(11) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_berater (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	lebenslauf int(11) unsigned NOT NULL DEFAULT '0',
	qualifikationsnachweise int(11) unsigned NOT NULL DEFAULT '0',
	standorte int(11) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_trainer (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	verwendung_babi smallint(1) unsigned NOT NULL DEFAULT '0',
	verwendung_psa smallint(1) unsigned NOT NULL DEFAULT '0',
	lebenslauf text,
	qualifikation_babi text NOT NULL DEFAULT '',
	lehr_befugnis text NOT NULL DEFAULT '',
	qualifikation_psa1 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa2 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa3 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa4 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa5 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa6 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa7 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa8 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa text NOT NULL DEFAULT '',
	qualifikation_psa_kommentar text NOT NULL DEFAULT '',
	anerkennung_pp3 smallint(1) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_stammdaten (
	name varchar(255) NOT NULL DEFAULT '',
	nachweis int(11) unsigned NOT NULL DEFAULT '0',
	rechtsform int(11) DEFAULT '0' NOT NULL,
	strasse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	seit int(11) NOT NULL DEFAULT '0',
	website varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	telefon varchar(255) NOT NULL DEFAULT '',
	leitbild varchar(255) NOT NULL DEFAULT '',
	leitbild_datei int(11) unsigned NOT NULL DEFAULT '0',
	qms_zertifikat_datei int(11) unsigned NOT NULL DEFAULT '0',
	qms_zertifikat text NOT NULL DEFAULT '',
	qms_typ int(11) DEFAULT '0' NOT NULL,
	zertifikat_bis int(11) NOT NULL DEFAULT '0',
	qualitaet_sicherung text,
	qualitaet_sicherung_datei int(11) unsigned NOT NULL DEFAULT '0',
	qualitaet_personal text,
	qualitaet_personal_datei int(11) unsigned NOT NULL DEFAULT '0',
	tr_pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	pruefbescheid text,
	pruefbescheid_datei int(11) unsigned NOT NULL DEFAULT '0',
	pruefbescheid_bis int(11) NOT NULL DEFAULT '0',
	standorte int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_angebotverantwortlich (
	ansuchen int(11) unsigned DEFAULT '0' NOT NULL,
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	telefon varchar(255) NOT NULL DEFAULT '',
	verantwortlich smallint(1) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE fe_users (
	name varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	tr_admin smallint(1) unsigned NOT NULL DEFAULT '0'
);
