CREATE TABLE tx_ieb_domain_model_ansuchen (
	name varchar(255) NOT NULL DEFAULT '',
	version int(11) NOT NULL DEFAULT '0',
	version_based_on int(11) NOT NULL DEFAULT '0',
	version_active smallint(1) unsigned NOT NULL DEFAULT '0',
	nummer varchar(255) NOT NULL DEFAULT '',
	akkreditierung_datum datetime DEFAULT NULL,
	einreich_datum datetime DEFAULT NULL,
	zuteilung_datum varchar(255) NOT NULL DEFAULT '',
	akkreditierung_entscheidung_datum datetime DEFAULT NULL,
	typ int(11) DEFAULT '0' NOT NULL,
	bundesland int(11) DEFAULT '0' NOT NULL,
	uebersicht_text text NOT NULL DEFAULT '',
	uebersicht_datei int(11) unsigned DEFAULT '0',
	zielgruppen_ansprache text NOT NULL DEFAULT '',
	zielgruppen_ansprache_datei int(11) unsigned DEFAULT '0',
	fernlehre smallint(1) unsigned NOT NULL DEFAULT '0',
	kinderbetreuung smallint(1) unsigned NOT NULL DEFAULT '0',
	lernziele int(11) unsigned DEFAULT '0',
	lernstandserhebung int(11) unsigned DEFAULT '0',
	diversity int(11) unsigned DEFAULT '0',
	didaktik_kommentar text,
	beratung_text text,
	beratung_datei int(11) unsigned DEFAULT '0',
	review_b1_comment_internal text NOT NULL DEFAULT '',
	review_b1_comment_internal_step text NOT NULL DEFAULT '',
	review_b1_comment_tr text NOT NULL DEFAULT '',
	review_b1_status int(11) DEFAULT '0' NOT NULL,
	review_b2_comment_internal text NOT NULL DEFAULT '',
	review_b2_comment_internal_step text NOT NULL DEFAULT '',
	review_b2_comment_tr text NOT NULL DEFAULT '',
	review_b2_status int(11) DEFAULT '0' NOT NULL,
	review_c1_comment_internal text NOT NULL DEFAULT '',
	review_c1_comment_internal_step text NOT NULL DEFAULT '',
	review_c1_comment_tr text NOT NULL DEFAULT '',
	review_c1_status int(11) DEFAULT '0' NOT NULL,
	review_c2_comment_internal text NOT NULL DEFAULT '',
	review_c2_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_comment_tr text NOT NULL DEFAULT '',
	review_c2_status int(11) DEFAULT '0' NOT NULL,
	review_c3_comment_internal text NOT NULL DEFAULT '',
	review_c3_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_comment_tr text NOT NULL DEFAULT '',
	review_c3_status int(11) DEFAULT '0' NOT NULL,
	review_total_comment_internal text NOT NULL DEFAULT '',
	review_total_comment_internal_step text NOT NULL DEFAULT '',
	review_total_comment_tr text NOT NULL DEFAULT '',
	review_total_status int(11) DEFAULT '0' NOT NULL,
	review_total_frist bigint(11) NOT NULL DEFAULT '0',
	locked_by int(11) NOT NULL DEFAULT '0',
	status int(11) DEFAULT '0' NOT NULL,
	ok smallint(1) unsigned NOT NULL DEFAULT '0',
	pruefbescheid_datei int(11) unsigned DEFAULT '0',
	pruefbescheid text,
	kooperation_datei int(11) unsigned DEFAULT '0',
	kooperation text,
	standort_erklaerung smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz1 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz2 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz3 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz4 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz5 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz6 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz7 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz8 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz9 smallint(1) unsigned NOT NULL DEFAULT '0',
	erklaerungd1 smallint(1) unsigned NOT NULL DEFAULT '0',
	erklaerungd2 smallint(1) unsigned NOT NULL DEFAULT '0',
	erklaerungd3 smallint(1) unsigned NOT NULL DEFAULT '0',
	kompetenz_text1 varchar(255) NOT NULL DEFAULT '',
	erklaerung_teil_a smallint(1) unsigned NOT NULL DEFAULT '0',
	erklaerung_teil_b smallint(1) unsigned NOT NULL DEFAULT '0',
	erklaerungd5 smallint(1) unsigned NOT NULL DEFAULT '0',
	copy_stammdaten mediumtext NOT NULL DEFAULT '',
	copy_trainer mediumtext NOT NULL DEFAULT '',
	copy_berater mediumtext NOT NULL DEFAULT '',
	copy_verantwortliche text NOT NULL DEFAULT '',
	copy_verantwortliche_mail text NOT NULL DEFAULT '',
	copy_standorte text NOT NULL DEFAULT '',
	review_b14_comment_internal text NOT NULL DEFAULT '',
	review_b14_comment_internal_step text NOT NULL DEFAULT '',
	review_b14_comment_tr text NOT NULL DEFAULT '',
	review_b14_status int(11) DEFAULT '0' NOT NULL,
	review_b15_comment_internal text NOT NULL DEFAULT '',
	review_b15_comment_internal_step text NOT NULL DEFAULT '',
	review_b15_comment_tr text NOT NULL DEFAULT '',
	review_b15_status int(11) DEFAULT '0' NOT NULL,
	review_b22_comment_internal text NOT NULL DEFAULT '',
	review_b22_comment_internal_step text NOT NULL DEFAULT '',
	review_b22_comment_tr text NOT NULL DEFAULT '',
	review_b22_status int(11) DEFAULT '0' NOT NULL,
	review_b23_comment_internal text NOT NULL DEFAULT '',
	review_b23_comment_internal_step text NOT NULL DEFAULT '',
	review_b23_comment_tr text NOT NULL DEFAULT '',
	review_b23_status int(11) DEFAULT '0' NOT NULL,
	upcoming_status int(11) DEFAULT '0' NOT NULL,
	gutachter_locked_by int(11) NOT NULL DEFAULT '0',
	notitzzettel text NOT NULL DEFAULT '',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0',
	trotzdem_abschicken text NOT NULL DEFAULT '',
	review_total_frist_mail_sent14t int(11) NOT NULL DEFAULT '0',
	review_total_frist_mail_sent1t int(11) NOT NULL DEFAULT '0',
	review_frist_pruefbescheid bigint(11) NOT NULL DEFAULT '0',
	review_frist_pruefbescheid_mail_sent14t int(11) NOT NULL DEFAULT '0',
	review_frist_pruefbescheid_mail_sent1t int(11) NOT NULL DEFAULT '0',
	status_after_review int(11) NOT NULL DEFAULT '0',
	ende int(11) NOT NULL DEFAULT '0',
	pruefbescheid_check int(11) DEFAULT '0' NOT NULL,
	status_ag_eins int(11) DEFAULT '0' NOT NULL,
	status_ag_zwei int(11) DEFAULT '0' NOT NULL,
	review_verrechnung_check1 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_verrechnung_check2 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_verrechnung1 text NOT NULL DEFAULT '',
	review_verrechnung2 text NOT NULL DEFAULT '',
	einzelunterricht smallint(1) unsigned NOT NULL DEFAULT '0',
	pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_b1_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b14_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b1_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b14_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b1_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_b14_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_b15_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b2_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b22_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b23_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c1_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_total_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_b15_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b2_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b22_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b23_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c1_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_total_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_b15_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_b2_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_b22_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_b23_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_c1_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_total_ag2_comment_internal_step text NOT NULL DEFAULT '',
	verantwortliche int(11) unsigned NOT NULL DEFAULT '0',
	verantwortliche_mail int(11) unsigned NOT NULL DEFAULT '0',
	kopie_von int(11) unsigned DEFAULT '0',
	stammdaten int(11) unsigned DEFAULT '0',
	standorte int(11) unsigned NOT NULL DEFAULT '0',
	trainer int(11) unsigned NOT NULL DEFAULT '0',
	berater int(11) unsigned NOT NULL DEFAULT '0',
	gutachter1 int(11) unsigned DEFAULT '0',
	gutachter2 int(11) unsigned DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_standort (
	name varchar(255) NOT NULL DEFAULT '',
	adresse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	pruef_bescheid smallint(1) unsigned DEFAULT '0',
	koop_schule text NOT NULL DEFAULT '',
	koop_schule_datei int(11) unsigned DEFAULT '0',
	ok smallint(1) unsigned NOT NULL DEFAULT '0',
	locked_by int(11) NOT NULL DEFAULT '0',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE tx_ieb_domain_model_berater (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	lebenslauf int(11) unsigned DEFAULT '0',
	qualifikationsnachweise int(11) unsigned DEFAULT '0',
	lebenslauf_kommentar varchar(255) NOT NULL DEFAULT '',
	qualifikationsnachweise_kommentar text NOT NULL DEFAULT '',
	ok smallint(1) unsigned NOT NULL DEFAULT '0',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c3_status int(11) DEFAULT '0' NOT NULL,
	review_c32_status int(11) DEFAULT '0' NOT NULL,
	review_c3_comment_internal text NOT NULL DEFAULT '',
	review_c3_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_comment_tr text NOT NULL DEFAULT '',
	locked_by int(11) NOT NULL DEFAULT '0',
	status_after_review int(11) NOT NULL DEFAULT '0',
	review_frist bigint(11) NOT NULL DEFAULT '0',
	review_frist_mail_sent14t int(11) NOT NULL DEFAULT '0',
	review_frist_mail_sent1t int(11) NOT NULL DEFAULT '0',
	pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	gutachter_locked_by int(11) NOT NULL DEFAULT '0',
	review_c3_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c3_ag2_comment_internal_step text NOT NULL DEFAULT ''
);

CREATE TABLE tx_ieb_domain_model_trainer (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	verwendung_babi smallint(1) unsigned NOT NULL DEFAULT '0',
	verwendung_psa smallint(1) unsigned NOT NULL DEFAULT '0',
	lebenslauf text,
	qualifikation_babi text NOT NULL DEFAULT '',
	lehr_befugnis text NOT NULL DEFAULT '',
	qualifikation_psa1 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa2 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa3 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa4 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa5 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa6 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa7 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa8 smallint(1) unsigned NOT NULL DEFAULT '0',
	qualifikation_psa text NOT NULL DEFAULT '',
	qualifikation_psa_kommentar text NOT NULL DEFAULT '',
	anerkennung_pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	lebenslauf_datei int(11) unsigned DEFAULT '0',
	qualifikation_babi_datei int(11) unsigned DEFAULT '0',
	lehr_befugnis_datei int(11) unsigned DEFAULT '0',
	qualifikation_psa_datei int(11) unsigned DEFAULT '0',
	okbabi smallint(1) unsigned NOT NULL DEFAULT '0',
	okpsa smallint(1) unsigned NOT NULL DEFAULT '0',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c21_babi_status int(11) DEFAULT '0' NOT NULL,
	review_c21_psa_status int(11) DEFAULT '0' NOT NULL,
	review_c22_babi_status int(11) DEFAULT '0' NOT NULL,
	review_c22_psa_status int(11) DEFAULT '0' NOT NULL,
	review_c22_quali1 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali2 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali3 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali4 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali5 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali6 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali7 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c22_quali8 smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c2_babi_comment_internal text NOT NULL DEFAULT '',
	review_c2_babi_comment_tr text NOT NULL DEFAULT '',
	review_c2_psa_comment_internal text NOT NULL DEFAULT '',
	review_c2_psa_comment_tr text NOT NULL DEFAULT '',
	review_c2_psa_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_babi_comment_internal_step text NOT NULL DEFAULT '',
	review_frist bigint(11) NOT NULL DEFAULT '0',
	locked_by int(11) NOT NULL DEFAULT '0',
	review_frist_mail_sent14t int(11) NOT NULL DEFAULT '0',
	review_frist_mail_sent1t int(11) NOT NULL DEFAULT '0',
	status_after_review_babi int(11) NOT NULL DEFAULT '0',
	status_after_review_psa int(11) NOT NULL DEFAULT '0',
	pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	gutachter_locked_by int(11) NOT NULL DEFAULT '0',
	review_c2_babi_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_psa_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_babi_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_psa_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_babi_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_c2_psa_ag2_comment_internal_step text NOT NULL DEFAULT '',
);

CREATE TABLE tx_ieb_domain_model_stammdaten (
	name varchar(255) NOT NULL DEFAULT '',
	markenname varchar(255) NOT NULL DEFAULT '',
	nachweis int(11) unsigned DEFAULT '0',
	rechtsform int(11) DEFAULT '0' NOT NULL,
	strasse varchar(255) NOT NULL DEFAULT '',
	plz int(11) NOT NULL DEFAULT '0',
	ort varchar(255) NOT NULL DEFAULT '',
	seit varchar(255) NOT NULL DEFAULT '',
	website varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	telefon varchar(255) NOT NULL DEFAULT '',
	leitbild text NOT NULL DEFAULT '',
	leitbild_datei int(11) unsigned DEFAULT '0',
	qms_zertifikat_datei int(11) unsigned DEFAULT '0',
	qms_zertifikat text NOT NULL DEFAULT '',
	qms_typ int(11) DEFAULT '0' NOT NULL,
	qualitaet_sicherung text,
	zertifikat_bis int(11) NOT NULL DEFAULT '0',
	qualitaet_sicherung_datei int(11) unsigned DEFAULT '0',
	qualitaet_personal text,
	qualitaet_personal_datei int(11) unsigned DEFAULT '0',
	tr_pp3 smallint(1) unsigned NOT NULL DEFAULT '0',
	locked_by int(11) NOT NULL DEFAULT '0',
	ok smallint(1) unsigned NOT NULL DEFAULT '0',
	weiterbildung_erklaerung smallint(1) unsigned NOT NULL DEFAULT '0',
	review_a1_status int(11) DEFAULT '0' NOT NULL,
	review_a1_comment_internal text NOT NULL DEFAULT '',
	review_a1_comment_tr text NOT NULL DEFAULT '',
	review_a1_comment_internal_step text NOT NULL DEFAULT '',
	review_a2_status int(11) DEFAULT '0' NOT NULL,
	review_a2_comment_internal text NOT NULL DEFAULT '',
	review_a2_comment_internal_step text NOT NULL DEFAULT '',
	review_a2_comment_tr text NOT NULL DEFAULT '',
	review_oecert_frist bigint(11) NOT NULL DEFAULT '0',
	review_oecert_frist_mail_sent14t int(11) NOT NULL DEFAULT '0',
	review_oecert_frist_mail_sent1t int(11) NOT NULL DEFAULT '0',
	status_after_review int(11) NOT NULL DEFAULT '0',
	review_a1_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_a2_gs_comment_internal_step text NOT NULL DEFAULT '',
	review_a1_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_a2_ag1_comment_internal_step text NOT NULL DEFAULT '',
	review_a1_ag2_comment_internal_step text NOT NULL DEFAULT '',
	review_a2_ag2_comment_internal_step text NOT NULL DEFAULT ''
);

CREATE TABLE tx_ieb_domain_model_angebotverantwortlich (
	nachname varchar(255) NOT NULL DEFAULT '',
	vorname varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	telefon varchar(255) NOT NULL DEFAULT '',
	verantwortlich smallint(1) unsigned NOT NULL DEFAULT '0',
	lebenslauf_datei int(11) unsigned DEFAULT '0',
	lebenslauf varchar(255) NOT NULL DEFAULT '',
	ok smallint(1) unsigned NOT NULL DEFAULT '0',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c1_babi smallint(1) unsigned NOT NULL DEFAULT '0',
	review_c1_psa smallint(1) unsigned NOT NULL DEFAULT '0',
	status_after_review int(11) NOT NULL DEFAULT '0'
);

CREATE TABLE fe_users (
	name varchar(255) NOT NULL DEFAULT '',
	email varchar(255) NOT NULL DEFAULT '',
	tr_admin smallint(1) unsigned NOT NULL DEFAULT '0',
	archiviert smallint(1) unsigned NOT NULL DEFAULT '0',
	ausschluss text NOT NULL DEFAULT ''
);

CREATE TABLE tx_ieb_domain_model_textbausteine (
	kriterium text NOT NULL DEFAULT '',
	baustein text NOT NULL DEFAULT ''
);

## EXTENSION BUILDER DEFAULTS END TOKEN - Everything BEFORE this line is overwritten with the defaults of the extension builder

CREATE TABLE fe_users (
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE tx_ieb_domain_model_trainer (
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE tx_ieb_domain_model_ansuchen (
  akkreditierung_pdf int(11) unsigned NOT NULL DEFAULT '0',
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE tx_ieb_domain_model_angebotverantwortlich (
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE tx_ieb_domain_model_berater (
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE tx_ieb_domain_model_stammdaten (
  import int(11) unsigned NOT NULL DEFAULT '0'
);
CREATE TABLE sys_file (
 import varchar(255) NOT NULL DEFAULT ''
);
CREATE TABLE sys_file_reference (
  import varchar(255) NOT NULL DEFAULT ''
);