sync:
  staging:
    path: "./public/"

    connection:
      ssh: ieb-staging

    filesystem:
      - path: /var/www/vhosts/901414.jweiland-hosting.de/httpdocs/typo3cms/ieb/public/
        filter:
          exclude:
            - .htaccess*
            - typo3conf/*
            - typo3temp/
            - typo3/
            - index.php
            - fileadmin/_processed_
        options:
          generate-stubs: false
    database:
      - type: mysql
        database: u901414_akdb
        user: interax_1
        password: X7vk8a5Keee$e6Cgg
        hostname: db.mariadb103
        port: 3306
        filter:
          exclude:
            - be_sessions
            - fe_sessions
          include:
        local:
          database: db
          connection:
            docker: ddev-ieb-db
        options:
          clear-database: false


#########################
## Deploy
#########################
deploy:
  staging:
    path: "./"

    connection:
      ssh: ieb-staging

    filesystem:
      - path: /var/www/vhosts/901414.jweiland-hosting.de/httpdocs/typo3cms/ieb/
        filter:
          exclude:
            - var/
            - public/
            - public/
            - /db/
            - /backup/

    _database:
          - type: mysql
            database: u901414_akdb
            user: interax_1
            password: X7vk8a5Keee$e6Cgg
            hostname: db.mariadb103
            filter:
              exclude:
              include:
            local:
              database: db
              connection:
                docker: ddev-ieb-db
            options:
              clear-database: false

